
def failTest():
    print( "fail" )
    raise Exception()